### ISSUE TITLE
Error when Building Wheel for Gym

### ISSUE THREAD

**Issue by Zach-Attach** [buildingamind/NewbornEmbodiedTuringTest#12]
**Describe the bug**
Installation of `nett-benchmarks` results in error when building wheel for gym. Installation works, but this increases installation time and may cause users to think that there is a problem with the code.

**To Reproduce**
1. `pip install nett-benchmarks`
2. During install, prints the following:
```
Building wheel for gym (setup.py) ... error
ERROR: Command errored out with exit status 1:
command: <PYTHON_DIR> -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-installgym_9aaa65d993704e14bd6fab28427dc2cf/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(file);code=f.read().replace('"'"'\r\n'heel-krklsetf

ERROR: Failed building wheel for gym

but then eventually this was printed:

DEPRECATION: gym was installed using the legacy 'setup.py install' method, because a wheel could not be built for it. A possible repls://github.com/https://github.com/pypa/pip/issues/8368.
```

**Expected behavior**
It should either be able to build the wheel or skip the process altogether.

**Comment by desaibhargav** [comment]
Hi @Zach-Attach, thanks for reporting this. Even though the installation succeeds, I agree this is quite an annoying thing for the user to see. The problem is that we're using an obsolete version of `gym` which only installs using the legacy method (as the message says). The installation fails with later `pip` or `setuptools` versions. 

We could change the installation instructions to run with `pip install -q nett-benchmarks` which should suppress most of the installation messages, but I don't see another way to get a clean install other than to upgrade `gym` which currently isn't possible due to `mlagents`.

**Comment by Zach-Attach** [comment]
Look like the solution is to change wheel version to 0.38.4 see [this comment](https://github.com/openai/gym/issues/3202#issuecomment-1513593788)
