### ISSUE TITLE
No analysis dir inside src dir

### ISSUE THREAD

**Issue by L-Pandey** [buildingamind/NewbornEmbodiedTuringTest#15]
**Describe the bug**
The main branch does not have the analysis directory and r scripts. 

**To Reproduce**

**Expected behavior**
As per the instructions in the document, the analysis script should be present here - src/analysis/. I cannot find the analysis dir in src.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Zach-Attach** [comment]
Seems like this is in `dev` but not in `main`. I believe @desaibhargav is working on the analysis code as of now, so I will assign to him.

**Comment by desaibhargav** [comment]
Hi @L-Pandey, thanks for reporting this. As @Zach-Attach mentions, I'm integrating the analysis as part of the library experience, so that the user only need call the `.analyze()` method after the `.run()` method and that will automatically produce the necessary benchmarking graphs. 

This is part of the v0.2 release, expected to go live today.

**Comment by Zach-Attach** [comment]
This appears to have been fixed in `dev` so I am closing.
