### ISSUE TITLE
Conversion Guide: example for the arguments of run_analysis.py

### ISSUE THREAD

**Issue by ssheybani** [buildingamind/NewbornEmbodiedTuringTest#17]
**Is your feature request related to a problem? Please describe.**

Since running the experiments produces a hierarchy of directories, It can be confusing which subdirectory should be used for log_dir. Adding a quick example can be helpful.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by desaibhargav** [comment]
Hi @ssheybani, thanks for bringing this up. You're totally right. I'm currently working on integrating the analysis part of the legacy codebase into the library so that the analysis can be do within the library itself by using the `.analyze()` call to the `NETT` class. This is part of the v0.2 release, expected to go live today.
