### ISSUE TITLE
Unnecessary Dependencies

### ISSUE THREAD

**Issue by Zach-Attach** [buildingamind/NewbornEmbodiedTuringTest#29]
**Is your feature request related to a problem? Please describe.**
Some dependencies appear to be unnecessary or a superset of what we actually use. Slowing down installation performance and taking up more storage than is necessary. This could also pose issues when unversioned requirements update and remove dependencies, breaking the code without any changes on our part.

**Describe the solution you'd like**
The following dependencies are not directly mentioned in the code.
- imageio-ffmpeg - unclear what it is being used for here
- scipy - not directly used, although its dependencies (numpy, pandas, matplotlib) are
-  ipywidgets - used for running the jupyter notebooks but is not needed for the actual package itself
Note: tqdm is also used, but unclear where this is being imported from

**Comment by desaibhargav** [comment]
Hi @Zach-Attach, thanks for raising this issue. 

For `spicy`, I have dropped it as a dependency in the [latest release](https://github.com/buildingamind/NewbornEmbodiedTuringTest/blob/release/v0.15/pyproject.toml) of the library. In the previous code it was being imported into the module for DVS wrapper, however it wasn't used. See [here](https://github.com/buildingamind/NewbornEmbodiedTuringTest/pull/33)

For `imageio-ffmpeg`, it is not directly used in the code, but is a required internal dependency when using modules to record videos in the simulation. 

For `ipywidgets`, you're right it's not needed for the actual package, just for `tqdm`. Since we probably want to have progress bars enabled in the code by default and we support Jupyter execution, instead of frustrating the user with an error message for `ipywidgets`, I thought adding it as a dependency explicitly would improve their experience.

**Comment by Zach-Attach** [comment]
Removed unnecessary dependencies in this update (with a typo)
